## Sprint 1 — Importação e reconhecimento dos dados

- [ ] Importar a base com `pandas`
- [ ] Verificar número de registros
- [ ] Verificar número e nomes das colunas
- [ ] Verificar tipos de dados
- [ ] Visualizar os primeiros registros
- [ ] Obter uma visão inicial da estrutura da base

**Resultado esperado:** fotografia inicial da base.

## Importando Bibliotecas

In [2]:
import pandas as pd
import numpy as np

## Leitura inicial da base

In [3]:
df = pd.read_csv("../data/Base Varejo.csv")

## Visualização inicial: Primeiras 5 linhas

In [4]:
df.head()

  DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0  01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1  01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2  01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3  01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4  01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...

## Reconhecimento inicial da estrutura da base

Na primeira tentativa de leitura, o arquivo foi interpretado como uma única
coluna. A inspeção do conteúdo indicou que os campos da base utilizam
ponto e vírgula (`;`) como delimitador.

Após ajustar a leitura com `sep=";"`, as colunas foram separadas corretamente.

A leitura inicial também revelou a presença de quatro colunas identificadas
pelo pandas como `Unnamed: 10`, `Unnamed: 11`, `Unnamed: 12` e `Unnamed: 13`.

Essas colunas serão investigadas nas próximas etapas para verificar se
correspondem a campos vazios no arquivo ou a alguma inconsistência na estrutura
dos dados.

### Leitura utilizada

```python
df = pd.read_csv("../data/Base Varejo.csv", sep=";")

In [5]:
df = pd.read_csv("../data/Base Varejo.csv", sep=";")

In [6]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

# Visualização inicial: Últimas 5 linhas

In [9]:
df.tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

## Identificação do a dimen~sao do datframe: número de linhas e colunas

In [7]:
df.shape

(830000, 14)

## Estrutura e informações gerais da base: número de entradas/registros; número e nome das colunas, quantidade de valores não nulos; tipos de dados; usos aproximado de memória.

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

## Observações sobre a estrutura da base

A análise do `df.info()` permitiu identificar:

- A base possui **830.000 registros e 14 colunas**.
- As colunas `DATA`, `CL_GENERO`, `CL_SEG`, `PR_CAT` e `PR_NOME` estão como `str`.
- As colunas `CO_ID`, `CL_ID`, `CL_EC`, `CL_FHL` e `PR_ID` estão como `int64`.
- As colunas `Unnamed: 10`, `Unnamed: 11`, `Unnamed: 12` e `Unnamed: 13` apresentam **0 valores não nulos**, indicando que estão completamente vazias.
- A coluna `DATA` está armazenada como `str` e deverá ser avaliada para conversão de tipo em etapa posterior.
- As colunas vazias e demais possíveis valores ausentes serão investigados e tratados nas etapas de limpeza previstas no projeto.

## Tipos de dados das colunas

In [10]:
df.dtypes

DATA               str
CO_ID            int64
CL_ID            int64
CL_GENERO          str
CL_EC            int64
CL_FHL           int64
CL_SEG             str
PR_ID            int64
PR_CAT             str
PR_NOME            str
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

## Registro da verificação dos tipos

A verificação com `df.dtypes` confirma os tipos identificados no `df.info()`.

A coluna `DATA` está como `str` e as quatro colunas `Unnamed` estão como `float64`, embora não apresentem valores preenchidos. Esses pontos serão considerados nas etapas posteriores de transformação e limpeza.

## Nomes das colunas

In [11]:
df.columns

Index(['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG',
       'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13'],
      dtype='str')

## Conclusão da Sprint 1

A inspeção inicial permitiu reconhecer a estrutura da base, identificando
830.000 registros, 14 colunas, seus respectivos tipos de dados e a presença
de quatro colunas completamente vazias.

Também foi identificado que a coluna `DATA` está armazenada como `str`.

A fotografia inicial da base está concluída. As questões identificadas serão
tratadas nas etapas posteriores, conforme o roteiro do projeto.